### ISSUE TITLE
improve the sh installer

### ISSUE THREAD

**Issue by mh-cbon** [Masterminds/glide.sh#4]
Hi,

I m not sure how you happen to manage the sh installer when you release a new version.

I found out you could get ride of the `version` file with a command like this,

``` sh
  # find the latest tag
  if type "wget" > /dev/null; then
    LATEST=`wget -q --no-check-certificate -O - https://api.github.com/repos/${GH}/releases/latest`
  elif type "curl" > /dev/null; then
    LATEST=`curl -L https://api.github.com/repos/${GH}/releases/latest`
  fi
  LATEST=`echo "${LATEST}" | grep -E '"tag_name": "([^"]+)"' | cut -d '"' -f4`
VERSION=`echo ${LATEST}` # value of the last tag x.x.x
```

BTW, i would like to suggest to add `mkdir -p ${GOPATH}/bin`, it happened many times that my build failed on CI because my setup was dirty.

BTW², i shamelessly copied and improved your script into a centralized one i can use on all my repo, https://github.com/mh-cbon/latest/blob/master/install.sh,

HTH!

**Comment by mattfarina** [comment]
@mh-cbon thanks for the suggestions.

Why the `--no-check-certificate` flag on GitHub?

**Comment by mh-cbon** [comment]
good Q. I think i put it because i ran into some troubles, since then i kept it because I did not want the script to fail for that kind of errors.
I suppose a good test session would reveal that it is useless.

**Comment by mattfarina** [comment]
@mh-cbon Thanks again for the feedback.

I folded in wget/curl detection into the installer.

I reworked the version part to fetch from `LATEST_RELEASE_URL="https://api.github.com/repos/Masterminds/$PROJECT_NAME/releases/tags/$TAG"`. This way I can control the releases.

Tags are pushed before release binaries can be attached. Getting the latest, before binaries are pushed to the release, causes a problem. So, instead I can now flip the switch when the release is fully up on GitHub.

**Comment by mh-cbon** [comment]
> Tags are pushed before release binaries can be attached. Getting the latest, before binaries are pushed to the release, causes a problem.

yep. I face the same kind of problem when i use remote ci to build artifacts.
Sometimes the build will fail, thus the release is somehow invalid. (the dlder will find a release, but not the attached artifact :s)
For this kind of script i did not find a definitive answer, one workaround i found was to go through an extra binary (gh-api-cli dl-assets [args]) to dl the desired asset, but it requires to install that program prior the desired package. gh-api-cli will do the job to get a valid asset even though the latest release is somehow broken.

For debian, rpm, chocolatey packaging the problem is more reasonably solved.
They are provided through a repository of artifacts which needs to be updated on every release.
If the release build has failed, the repository remains untouched, so, at worst the client won t get the latest. But the workflow will continue to work.
Still not ideal, but yet more workable.
